### ISSUE TITLE
Error: "Could not connect to React dev server. Not running?"

### ISSUE THREAD

**Issue by flaektrem** [SchoofsKelvin/vscode-sshfs#279]
Suddenly i got this error when trying to edit connections or try to add new.
Tried reinstall extension and addon (using VSCode addon in Homeassistant)

Anyone know whats going on?

**Comment by SchoofsKelvin** [comment]
Can you post the `SSH FS` log? It is available under `Output > SSH FS`. While it should censor passwords/passphrases, I recommend checking it for (other) sensitive data first.

I have the feeling it's the VS Code add-on of Homeassistant running VS Code in non-production mode. My extension detects that, and then tries to use my React Dev server to load the Settings UI so I can hotreload it etc. Your Settings UI should still work fine without it, though.

I might add a flag to disable this "feature" manually. _Not really a feature of the extension, but more of a bug in that HA add-on that makes my extension think it's not running in production._

**Comment by flaektrem** [comment]
Here is what I got when first opened up the addon, then pressed "Create a SSH FS configuration".

```
[INFO]    Loading configurations...
[INFO]    Calculated config flags: {}
[INFO]    Found 0 configurations
[INFO]    Extension activated, version 1.21.1, mode 2
[INFO]    Loading configurations...
[INFO]    Loading configurations...
[INFO]    Found 0 configurations
[INFO]    Found 0 configurations
[DEBUG]   [WebView] Navigation requested: {
    "type": "newconfig"
}
[WARNING] [WebView] Error connecting to React dev server: Error: connect ECONNREFUSED 127.0.0.1:3000
Logged at:
	at ClientRequest.<anonymous> (/data/vscode/extensions/kelvin.vscode-sshfs-1.21.1/dist/425.extension.js:1:1281)
	at ClientRequest.emit (events.js:375:28)
	at Socket.socketErrorListener (_http_client.js:475:9)
Reported from WebView
```

**Comment by flaektrem** [comment]
> 
> 
> Can you post the `SSH FS` log? It is available under `Output > SSH FS`. While it should censor passwords/passphrases, I recommend checking it for (other) sensitive data first.
> 
> I have the feeling it's the VS Code add-on of Homeassistant running VS Code in non-production mode. My extension detects that, and then tries to use my React Dev server to load the Settings UI so I can hotreload it etc. Your Settings UI should still work fine without it, though.
> 
> I might add a flag to disable this "feature" manually. _Not really a feature of the extension, but more of a bug in that HA add-on that makes my extension think it's not running in production._

I wrote to the author of the HA addon about this issue. Now he asks how your SSH FS addon detects "development" mode?
Maybe this will help him understand whats wrong.

**Comment by SchoofsKelvin** [comment]
> Now he asks how your SSH FS addon detects "development" mode?
> Maybe this will help him understand whats wrong.

I basically check whether `ExtensionContext.extensionMode` is different from `vscode.ExtensionMode.Production`:
https://github.com/SchoofsKelvin/vscode-sshfs/blob/4eef87a7e8bfb4f8013c031381abb406dda11b46/src/extension.ts#L29-L32

**Comment by flaektrem** [comment]
HA guys cannot help me with this.

So did you get anything useful from my logs? @SchoofsKelvin

**Comment by SchoofsKelvin** [comment]
It's purely a visual issue, right? You see the warning whenever the window (re)loads, but the Settings UI otherwise works? _If the extension can't connect to the React dev server, it should fallback to the bundled Settings UI._

**Comment by flaektrem** [comment]
When I press "Create a SSH FS configuration", dev server message pops up and SSH FS tab is just blank and I cant do anything. 
SSH FS Extension settings seems to be ok.


Se attached pictures:


![vscode2](https://user-images.githubusercontent.com/58172129/129618438-c9c33768-8943-46d0-a5f6-6fc8de888347.JPG)
![vscode](https://user-images.githubusercontent.com/58172129/129618444-720cada2-908e-49dd-8a09-153a885060df.JPG)
![vscode3](https://user-images.githubusercontent.com/58172129/129618828-228eed94-d001-43ff-94eb-7c5b48986d85.JPG)

**Comment by SchoofsKelvin** [comment]
I was planning on changing `!== Production` into `=== Development` to make `undefined` not a false negative, but according to your logs the mode is already explicitly set to `vscode.ExtensionMode.Development`. I've read the issue on the HA repository, and assuming they didn't overlook anything, it indeed looks like an issue over at the `code-server` side. 

As a temporary fix, I added an environment variable `VSCODE_SSHFS_PRODUCTION` you can set which will force-disable the debug mode (48ef229). You can download the latest built version from [here](https://github.com/SchoofsKelvin/vscode-sshfs/actions/workflows/build-extension.yml?query=branch%3Amaster), starting from build number 54 and later. _Alternatively you could wait for v1.21.3 or later, but no plans on releasing an update right now._

**Comment by flaektrem** [comment]
Thanks!
But I´m sorry this is to advanced for me so I´ll think I have to wait for v1.21.3.
I don´t really understand what to download, where to put it and how to set the variable. I´m not a hacker 🥲 😄  
Thanks anyway

**Comment by darrillaga** [comment]
Hey @SchoofsKelvin , I'm pretty interested on trying the version you sent, I'll download it, how do I set the env variable?
Is it just setting in on the code-server terminal?

Thanks in advance!

**Comment by SchoofsKelvin** [comment]
@darrillaga I don't know exactly what OS you're using (on your pc or HA), so honestly I'd say Google it. It has to be set for the whole VS Code process tree.

I know in Windows you can use the "Edit the system environment variables" configuration option, and I assume on Unix-based systems you can edit some OS-specific file (e.g. `/etc/environment`) to add a system-wide variable. Alternatively if you're manually starting `code-server`, doing something like `VSCODE_SSHFS_PRODUCTION=true ./start.sh` or so might do the trick too.

**Comment by darrillaga** [comment]
I'm using android (Samsung Tab S7) with VH editor app (code-server + termux over android / Frankenstein style), trying to access a remote machine, I'll look around to see if I find a way

**Comment by FuzzyMistborn** [comment]
FYI i'm running into this even running code-server installed on bare metal.

**Comment by SchoofsKelvin** [comment]
Tomorrow I'll add the "inverse environment variable" and publish a new extension version with it soon afterwards. That should resolve this issue.

It still seems to be an issue specific to how `code-server` loads extensions, but the fix should make it no longer matter.

**Comment by SchoofsKelvin** [comment]
I just pushed a commit that should fix this issue. You can download the latest build from [here](https://github.com/SchoofsKelvin/vscode-sshfs/actions?query=branch%3Amaster), build 57 and higher. Could you test this version?

I'll probably publish an extension update (with the fix included) in a few days, depending on some other factors.

**Comment by flaektrem** [comment]
I don't know how to use that, sorry my friend.
I'll have to wait for that extension update I think.

**Comment by FuzzyMistborn** [comment]
Now I no longer get the react error, but the configuration page is completely blank.

**Comment by SchoofsKelvin** [comment]
> Now I no longer get the react error, but the configuration page is completely blank.

Hmm, I'll see if I can get `code-server` running and replicate the issue.

**Comment by FuzzyMistborn** [comment]
If you want an easy docker image the folks over at Linuxserver.io have a good one.

**Comment by flaektrem** [comment]
> 
> 
> I just pushed a commit that should fix this issue. You can download the latest build from [here](https://github.com/SchoofsKelvin/vscode-sshfs/actions?query=branch%3Amaster), build 57 and higher. Could you test this version?
> 
> I'll probably publish an extension update (with the fix included) in a few days, depending on some other factors.

Any extension update ready soon?

**Comment by TomS-** [comment]
https://github.com/cdr/code-server/discussions/4075

**Comment by flaektrem** [comment]
I think it's about the same problem. But im not able to solve it my self, sorry.

**Comment by SchoofsKelvin** [comment]
I was able to run `code-server` and replicate most of the issue:
- Opening the Settings UI produces the error
- The extension would still fallback to rendering the built version of the Settings UI
- Only right after install (and before I restarted `code-server`) did the "editor" remain black, trying to reproduce this again

Commit 05e1b69 should fix the unnecessary error (at least extension-wise, still a `code-server` issue), but I'll still have to look into why it appeared blank once for me and continuously for others.

**Comment by jsjoeio** [comment]
Hey! code-server maintainer here 👋

I tested `v1.21.2` in code-server `v3.12.0` just now and the webview is loading as expected (I think). However, the "could not connect to React dev server" issue still appears. 

## Video

https://user-images.githubusercontent.com/3806031/134232342-5c896d7a-dab2-4bd5-b1c8-af86636b4555.mov



## Logs

These logs showed up in the browser while running SSH-FS

```javascript
console.ts:137 [Extension Host] Could not register source-map-support: Error: Cannot find module 'source-map-support/register'
Require stack:
- /Users/jp/.local/share/code-server/extensions/kelvin.vscode-sshfs-1.21.2/dist/extension.js
- /usr/local/Cellar/code-server/3.12.0/libexec/vendor/modules/code-oss-dev/out/vs/loader.js
- /usr/local/Cellar/code-server/3.12.0/libexec/vendor/modules/code-oss-dev/out/bootstrap-amd.js
- /usr/local/Cellar/code-server/3.12.0/libexec/vendor/modules/code-oss-dev/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
	at Function.Module._load (internal/modules/cjs/loader.js:745:27)
	at Function.u._load (/usr/local/Cellar/code-server/3.12.0/libexec/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:28329)
	at Function.E._load (/usr/local/Cellar/code-server/3.12.0/libexec/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:24906)
	at Function.o._load (/usr/local/Cellar/code-server/3.12.0/libexec/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:59872)
	at Module.require (internal/modules/cjs/loader.js:961:19)
	at Module.require (/usr/local/Cellar/code-server/3.12.0/libexec/vendor/modules/code-oss-dev/extensions/git/dist/main.js:2:515806)
	at require (internal/modules/cjs/helpers.js:92:18)
	at Object.4043 (/Users/jp/.local/share/code-server/extensions/kelvin.vscode-sshfs-1.21.2/dist/extension.js:1:25133)
	at i (/Users/jp/.local/share/code-server/extensions/kelvin.vscode-sshfs-1.21.2/dist/extension.js:1:25419)
	at Function.i.t (/Users/jp/.local/share/code-server/extensions/kelvin.vscode-sshfs-1.21.2/dist/extension.js:1:25638)
	at processTicksAndRejections (internal/process/task_queues.js:95:5)

[Extension Host] [WARNING] [WebView] Error connecting to React dev server: Error: connect ECONNREFUSED 127.0.0.1:3000Logged at:	at ClientRequest.<anonymous> (/Users/jp/.local/share/code-server/extensions/kelvin.vscode-sshfs-1.21.2/dist/425.extension.js:1:1281)	at ClientRequest.emit (events.js:400:28)	at ClientRequest.emit (domain.js:470:12)Reported from WebView

notificationsAlerts.ts:40 Could not connect to React dev server. Not running?

DevTools failed to load source map: Could not load content for https://vscode-remote+localhost-003a8080.vscode-resource.vscode-webview.net/Users/jp/.local/share/code-server/extensions/kelvin.vscode-sshfs-1.21.2/webview/build/static/css/main.1e99675e.chunk.css.map: Connection error: net::ERR_NAME_NOT_RESOLVED

data reducer {type: '@@redux/INITm.r.y.y.s.e'}
main.1919b231.chunk.js:1 data reducer {type: '@@redux/PROBE_UNKNOWN_ACTIONf.6.h.r.3'}
main.1919b231.chunk.js:1 data reducer {type: '@@redux/INITm.r.y.y.s.e'}
```

I don't think this is the root cause of the issue but it seems like the  Redux and/or React DevTools are enabled? Is this intentional? I'm seeing the logs for the store, dispatch and the reducers. I wouldn't expect to see those after installing the extension, but maybe that's normal.

**Comment by SchoofsKelvin** [comment]
For the React error, that should be fixed in v1.22.0, which is currently building and going through the release process right now. _So give or take 10 minutes._

The update will only include a fix that disables the React stuff (unless explicitly turned on using a specific environment variable), so the error notification should no longer appear. This shouldn't have an effect on the blank webview issue though.

**Comment by SchoofsKelvin** [comment]
> Seems like it's working, no? Or is there another blank webview issue we're talking about?

I personally wasn't able to reproduce the blank webview issue (although I only tried it using the latest version of `code-server`) so I'm not sure what triggers it. Perhaps @flaektrem or @FuzzyMistborn could try the latest version (of `code-server` and the extension) and see if they still have the issue, and if so provide the logs from DevTools (aka "Inspect Element", i.e. F12 or Ctrl+Shift+i)?

As for those warnings about source maps, those are normal. DevTools tries to load the source maps listed in the built JS files, but the extension doesn't bundle those, as they're unnecessary and would double the size of the packaged `.vsix` file.

**Comment by FuzzyMistborn** [comment]
Not sure this is what you're looking for but it's what pops up in the console when i try to open the configuration page.
![image](https://user-images.githubusercontent.com/16689090/134277207-4495a5a1-7bc4-47ce-b057-8c4165bcf712.png)

```
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can remove its sandboxing. code.example.com
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
Content Security Policy: The page’s settings blocked the loading of a resource at https://code.example.com/webview/service-worker.js?id=b149e1b2-f465-432e-af94-281bf25b9163&swVersion=2&extensionId=Kelvin.vscode-sshfs&platform=browser&vscode-resource-base-authority=vscode-resource.vscode-webview.net&parentOrigin=https%3A%2F%2Fcode.example.com (“script-src”).
Loading failed for the <script> with source “https://vscode-remote+code-002example-002ecom.vscode-resource.vscode-webview.net/config/extensions/kelvin.vscode-sshfs-1.22.0/webview/build/static/js/runtime-main.bundle.js”. index.html:116:1
Content Security Policy: The page’s settings blocked the loading of a resource at https://code.example.com/webview/service-worker.js?id=b149e1b2-f465-432e-af94-281bf25b9163&swVersion=2&extensionId=Kelvin.vscode-sshfs&platform=browser&vscode-resource-base-authority=vscode-resource.vscode-webview.net&parentOrigin=https%3A%2F%2Fcode.example.com (“script-src”).
Loading failed for the <script> with source “https://vscode-remote+code-002eexample-002ecom.vscode-resource.vscode-webview.net/config/extensions/kelvin.vscode-sshfs-1.22.0/webview/build/static/js/269.bundle.js”. index.html:116:1
Content Security Policy: The page’s settings blocked the loading of a resource at https://code.example.com/webview/service-worker.js?id=b149e1b2-f465-432e-af94-281bf25b9163&swVersion=2&extensionId=Kelvin.vscode-sshfs&platform=browser&vscode-resource-base-authority=vscode-resource.vscode-webview.net&parentOrigin=https%3A%2F%2Fcode.example.com (“script-src”).
Loading failed for the <script> with source “https://vscode-remote+code-002eexample-002ecom.vscode-resource.vscode-webview.net/config/extensions/kelvin.vscode-sshfs-1.22.0/webview/build/static/js/main.bundle.js”. index.html:116:1
```

**Comment by TomS-** [comment]
> > Seems like it's working, no? Or is there another blank webview issue we're talking about?
> 
> I personally wasn't able to reproduce the blank webview issue (although I only tried it using the latest version of `code-server`) so I'm not sure what triggers it. Perhaps @flaektrem or @FuzzyMistborn could try the latest version (of `code-server` and the extension) and see if they still have the issue, and if so provide the logs from DevTools (aka "Inspect Element", i.e. F12 or Ctrl+Shift+i)?
> 
> As for those warnings about source maps, those are normal. DevTools tries to load the source maps listed in the built JS files, but the extension doesn't bundle those, as they're unnecessary and would double the size of the packaged `.vsix` file.

Thanks for looking into this so quickly. I am also experiencing a blank screen with Docker accessing `code-server` through the IP address (not a domain - no reverse proxy). 

![image](https://user-images.githubusercontent.com/4595662/134322265-cb956560-8dba-4657-b221-b30d33fa6394.png)

This is what I'm receiving as an error.

**Comment by jsjoeio** [comment]
@FuzzyMistborn are you using HTTPS?

> Did a reverse proxy to serve over HTTPS:// and configured NGINX to allow WebSockets and it's working fine for me now :-)

@TomS-
Awesome! Yeah I was going to say it's probably an issue if you're not using HTTPS but sounds like you figured it out :)

**Comment by FuzzyMistborn** [comment]
I am.  I use Caddy, i"ll have to look into allowing websockets.

**Comment by jsjoeio** [comment]
Sounds good! It may help digging through [previous GitHub Discussions that mention Caddy](https://github.com/cdr/code-server/discussions?discussions_q=caddy) too (in case you weren't planning on doing that already).

**Comment by SchoofsKelvin** [comment]
I'll leave this issue open for now, although the problem seems to be how `code-server` handles webview URIs that point at extension resources. Looks like it might be a CORS issue.

**Comment by flaektrem** [comment]
Updated to latest version (1.22.0) of SSH FS now. That "Could not connect to..." error is gone. 
Now the tabs are blank, as someone mentioned above.

**Comment by SchoofsKelvin** [comment]
> Updated to latest version (1.22.0) of SSH FS now. That "Could not connect to..." error is gone.
Now the tabs are blank, as someone mentioned above.

That's normal, or at least expected. The blank tab issue is something `code-server` needs to fix, and I think is already working on.

**Comment by jsjoeio** [comment]
@flaektrem can you please [open a bug report](https://github.com/cdr/code-server/issues/new?assignees=&labels=&template=bug-report.md&title=) under code-server? We're determined to help get this fixed so @SchoofsKelvin can close this issue!

**Comment by flaektrem** [comment]
@jsjoeio I'm away from home for a couple of days and not able to gather all necessary information needed to open a bug report. Anyone else maybe?

**Comment by jsjoeio** [comment]
@flaektrem I mean there's no rush, but sure if anyone can open a bug report with steps to reproduce to get blank tabs, then we can help! Otherwise, it'll be hard to help y'all fix this.

**Comment by flaektrem** [comment]
@jsjoeio Sure I can open a bug report anyway but will lack a lot of information and I don't like that. I think that's not so popular

**Comment by jsjoeio** [comment]
@flaektrem well why not wait to open it when you're back home and have all the information needed?

**Comment by flaektrem** [comment]
At least I started somewhere.

**Comment by SchoofsKelvin** [comment]
I've tried it on Firefox and it indeed failed, here's some more information:
- `Content-Security-Policy`: `default-src 'none'; script-src 'unsafe-inline' https://*.vscode-webview.net; style-src 'unsafe-inline' https://*.vscode-webview.net;`
- Warning in console: `The web worker extension host is started without an iframe sandbox!` at `webWorkerExtensionHost.ts:143:13`
- Warning in console: `An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can remove its sandboxing.`
  - Explained [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox) that having both means you the `sandbox` is useless in general _(although I think that's from a malicious POV)_
- Example of script that fails to load: `https://vscode-remote+hetzner-002emorle-002ega-003a6443.vscode-resource.vscode-webview.net/root/.local/share/code-server/extensions/kelvin.vscode-sshfs-1.23.1/webview/build/static/js/runtime-main.bundle.js`
  ![image](https://user-images.githubusercontent.com/14597409/137358420-610897d5-adb9-4510-b553-21c74fc34a37.png)

Looking a bit at the code in devtools, it looks like the webview's iframe originally loads some empty `fake.html` and once that's loaded sets the content to the actual webview HTML (including the `<meta http-equiv="Content-Security-Policy" content="...">`). With how the warning in the console specifies `"script-src"` and not `"script-src 'unsafe-inline' etc"`, I have the feeling Firefox just can't deal with this dynamic way of loading/setting the webview HTML. _Not the first time Firefox has issues with [CSP in iframes](https://bugzilla.mozilla.org/show_bug.cgi?id=1407197)._

[This reported Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1721296) looks similar to what's happening here, except instead of `srcdoc` we're using `src` and that the CSP isn't using the defined policy at the top level while in our case it isn't used the defined policy in the inner frame.

This looks like it's a Firefox bug at this point. The extension sets the proper CSP which Chrome is fine with. Firefox seems to not recognize the CSP meta element.
